# Generated by Django 3.2 on 2021-05-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=150, verbose_name='ключ')),
                ('value', models.CharField(max_length=150, verbose_name='значение')),
                ('picture', models.ImageField(upload_to='pictures/icons/menu', verbose_name='картинка')),
            ],
            options={
                'verbose_name': 'контент меню',
                'verbose_name_plural': 'контент меню',
                'ordering': ['pk'],
            },
        ),
    ]
