# Generated by Django 3.2 on 2021-05-06 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menucontent',
            options={'ordering': ['pk'], 'verbose_name': 'контент', 'verbose_name_plural': 'контент меню'},
        ),
        migrations.AlterField(
            model_name='menucontent',
            name='value',
            field=models.TextField(max_length=500, verbose_name='значение'),
        ),
    ]
