# Generated by Django 3.2.2 on 2021-05-13 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210507_0141'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=150, verbose_name='ключ')),
                ('value', models.TextField(max_length=500, verbose_name='значение')),
            ],
            options={
                'verbose_name': 'контент',
                'verbose_name_plural': 'контент "О нас"',
                'ordering': ['pk'],
            },
        ),
    ]
