# Generated by Django 3.2.2 on 2021-05-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_aboutcontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='вопрос')),
                ('answer', models.CharField(max_length=500, verbose_name='ответ')),
            ],
            options={
                'verbose_name': 'вопрос',
                'verbose_name_plural': 'ответ',
                'ordering': ['pk'],
            },
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='value',
            field=models.TextField(max_length=2300, verbose_name='значение'),
        ),
    ]
