# Generated by Django 3.2 on 2021-05-06 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='название')),
                ('subscription', models.CharField(max_length=500, verbose_name='описание')),
                ('picture', models.ImageField(upload_to='icons/product', verbose_name='иконка')),
                ('cost', models.IntegerField(verbose_name='цена')),
                ('amount', models.IntegerField(verbose_name='количество выдаваемого золота')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
                'ordering': ['id'],
            },
        ),
    ]
