# Generated by Django 3.2 on 2021-05-06 20:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='количество выдаваемого золота'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='цена'),
        ),
    ]
