# Generated by Django 3.2.2 on 2021-05-19 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210507_0149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['cost'], 'verbose_name': 'товар', 'verbose_name_plural': 'товары'},
        ),
    ]
